### ISSUE TITLE
Howtouse?

### ISSUE THREAD

**Issue by MikkelDK** [RyderAsKing/GhostyAdminOfficial#3]
Hi,

How does this work? ^^
when I try typo: +getserverinfo 1 (from the database)

I getting some weird log:
```
/home/mikkel/discord/panel/GhostyAdminOfficial-master/commands/getserverinfo.js:21
  .setFooter('API Latency is ' + `${Date.now() - message.createdTimestamp}` + ' ms, Proudly Hosted by Ghosty.host', client.user.avatarURL()L)

SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.exports.run (/home/mikkel/discord/panel/GhostyAdminOfficial-master/events/message.js:19:17)
    at Client.<anonymous> (/home/mikkel/discord/panel/GhostyAdminOfficial-master/index.js:24:55)
    at Client.emit (events.js:315:20)
````

**Comment by Ssmidge** [comment]
An ")" Is missing somewhere in that code.

**Comment by AcktarOfficial** [comment]
Remove the extra L at the end lol. typo😅😬

client.user.avatarURL()*L*)

**Comment by Ssmidge** [comment]
I'm pretty sure Ryder abandoned this in the first place lol
